### PR TITLE
Android support

### PR DESCRIPTION
**Pull request by MAJigsaw77**
Just to prove that it works, i built a gradle app using the generated shared lib file from hxcpp and this is how it looks like.

Screenshot_20240618-003449

And this is the generated apk in any case.

[androidBuild.zip](https://github.com/user-attachments/files/15877550/androidBuild.zip)

### CODE REVIEW

**Comment by foreignsasquatch** [comment]
This is great! I haven't tested it yet but could you provide an example repo for this?

**Comment by MAJigsaw77** [comment]
> This is great! I haven't tested it yet but could you provide an example repo for this?

Sure

**Comment by MAJigsaw77** [comment]
@foreignsasquatch https://github.com/MAJigsaw77/raylib-hx-android-example

**Comment by foreignsasquatch** [comment]
Thank you :D

**Pull request merged**
